### ISSUE TITLE
JetToolbox for 2018

### ISSUE THREAD

**Issue by deepakcern** [cms-jet/JetToolbox#65]
Dear all,
I am looking for JetToolbox for 2018 but I see this is available for upto 94X.
Can you please let me know when this will be available for 10_2X so that we can start analysing 2018 data ASAP.

Thanks,
Deepak from bbDM Team

**Comment by alefisico** [comment]
Hi Deepak
(similar reply as in your private email)
Maybe the instructions are misleading, but we have tested the jetToolbox in releases up to 94X, but that does not mean that it does not work for newer realizes. I am not aware of any big change in the package that the jetToolbox relies on, so my guess is that it should work out of the box for 10_X.
Please let me know if you find something that does not work.
cheers,
